route:
  receiver: slack-notifications

receivers:
  - name: slack-notifications
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/your/slack/webhook'
        channel: '#alerts'
        text: "{{ .CommonAnnotations.summary }}"
